import { LakeScheduleLanesEntry } from "../../../../src/file-maker/types/duel-types.ts";

export const CLARK_WV8_GF: LakeScheduleLanesEntry = {
  id: 31982,
  lk_schd_id: 2384,
  racetime: "09:50:00",
  host: "Clark",
  event: "WV8 GF",
  entry0: "",
  entry1: "1st H1",
  entry2: "1st H2",
  entry3: "2nd H1",
  entry4: "2nd H2",
  entry5: "5th Fastest",
  entry6: "6th Fastest",
  racedate: "04/13/2024",
  racedatetime: "04/13/2024 09:50:00",
  clbType: "Col",
  entryseed0: "",
  entryseed1: "",
  entryseed2: "",
  entryseed3: "",
  entryseed4: "",
  entryseed5: "",
  gcal_error: "",
  gcal_eTag: "",
  gcal_status: "",
  entrydisp0: "",
  entrydisp1: "1st H1",
  entrydisp2: "1st H2",
  entrydisp3: "2nd H1",
  entrydisp4: "2nd H2",
  entrydisp5: "5th Fastest",
  entrydisp6: "6th Fastest",
  results_code_display:
    "Ln  Entry               \r-- --------------------\r1  1st H1\r2  1st H2\r3  2nd H1\r4  2nd H2\r5  5th Fastest\r6  6th Fastest\r",
  racedateUnix: "2024-04-13",
  entryseed6: "",
  order0: "",
  order1: "",
  order2: "",
  order3: "",
  order4: "",
  order5: "",
  order6: "",
  splitprev0: "",
  splitprev1: "",
  splitprev2: "",
  splitprev3: "",
  splitprev4: "",
  splitprev5: "",
  splitprev6: "",
  splitwin0: "",
  splitwin1: "",
  splitwin2: "",
  splitwin3: "",
  splitwin4: "",
  splitwin5: "",
  splitwin6: "",
  time0: "",
  time1: "",
  time2: "",
  time3: "",
  time4: "",
  time5: "",
  time6: "",
  SummaryHTML:
    "<tr><td>1</td><td>1st H1</td><td>&nbsp;</td><td align='right'>&nbsp;</td><td align='right'>&nbsp;</td></tr><tr><td>2</td><td>1st H2</td><td>&nbsp;</td><td align='right'>&nbsp;</td><td align='right'>&nbsp;</td></tr><tr><td>3</td><td>2nd H1</td><td>&nbsp;</td><td align='right'>&nbsp;</td><td align='right'>&nbsp;</td></tr><tr><td>4</td><td>2nd H2</td><td>&nbsp;</td><td align='right'>&nbsp;</td><td align='right'>&nbsp;</td></tr><tr><td>5</td><td>5th Fastest</td><td>&nbsp;</td><td align='right'>&nbsp;</td><td align='right'>&nbsp;</td></tr><tr><td>6</td><td>6th Fastest</td><td>&nbsp;</td><td align='right'>&nbsp;</td><td align='right'>&nbsp;</td></tr>",
  competitorList:
    "Clark, MT Holyoke, 1st H1, 2nd H1, 3rd H1, 4th H1, 5th H1, 6th H1, 1st H2, 2nd H2, 3rd H2, 4th H2, 5th H2, 6th H2",
};

export const HCR_WV8_SCHEDULED: LakeScheduleLanesEntry = {
  id: 31984,
  lk_schd_id: 2416,
  racetime: "10:10:00",
  event: "WV8",
  host: "Holy Cross",
  entry0: "",
  entry1: "Holy Cross",
  entry2: "Smith",
  entry3: "Colgate",
  entry4: "",
  entry5: "",
  entry6: "",
  racedate: "04/13/2024",
  racedatetime: "04/13/2024 10:10:00",
  clbType: "Col",
  entryseed0: "",
  entryseed1: "",
  entryseed2: "",
  entryseed3: "",
  entryseed4: "",
  entryseed5: "",
  gcal_error: "",
  gcal_eTag: "",
  gcal_status: "",
  entrydisp0: "",
  entrydisp1: "Holy Cross",
  entrydisp2: "Smith",
  entrydisp3: "Colgate",
  entrydisp4: "",
  entrydisp5: "",
  entrydisp6: "",
  results_code_display:
    "Ln  Entry               \r-- --------------------\r1  Holy Cross\r2  Smith\r3  Colgate\r",
  racedateUnix: "2024-04-13",
  entryseed6: "",
  order0: "",
  order1: "",
  order2: "",
  order3: "",
  order4: "",
  order5: "",
  order6: "",
  splitprev0: "",
  splitprev1: "",
  splitprev2: "",
  splitprev3: "",
  splitprev4: "",
  splitprev5: "",
  splitprev6: "",
  splitwin0: "",
  splitwin1: "",
  splitwin2: "",
  splitwin3: "",
  splitwin4: "",
  splitwin5: "",
  splitwin6: "",
  time0: "",
  time1: "",
  time2: "",
  time3: "",
  time4: "",
  time5: "",
  time6: "",
  SummaryHTML:
    "<tr><td>1</td><td>Holy Cross</td><td>&nbsp;</td><td align='right'>&nbsp;</td><td align='right'>&nbsp;</td></tr><tr><td>2</td><td>Smith</td><td>&nbsp;</td><td align='right'>&nbsp;</td><td align='right'>&nbsp;</td></tr><tr><td>3</td><td>Colgate</td><td>&nbsp;</td><td align='right'>&nbsp;</td><td align='right'>&nbsp;</td></tr>",
  competitorList:
    "Holy Cross, Holy Cross, Colgate, Smith, 1st fastest, 2nd fastest, 3rd fastest, 1st H1, 2nd H1, 3rd H1, 4th H1, 5th H1, 6th H1, 1st H2, 2nd H2, 3rd H2, 4th H2, 5th H2, 6th H2",
};

export const WPI_MV8_RESULTS: LakeScheduleLanesEntry = {
  id: 31951,
  lk_schd_id: 2389,
  racetime: "09:40:00",
  event: "MV8",
  host: "WPI",
  entry0: "",
  entry1: "Wesleyan",
  entry2: "WPI",
  entry3: "Colby",
  entry4: "Hamilton",
  entry5: "",
  entry6: "",
  racedate: "04/06/2024",
  racedatetime: "04/06/2024 09:40:00",
  clbType: "Col",
  entryseed0: "",
  entryseed1: "",
  entryseed2: "",
  entryseed3: "",
  entryseed4: "",
  entryseed5: "",
  gcal_error: "",
  gcal_eTag: "",
  gcal_status: "",
  entrydisp0: "",
  entrydisp1: "Wesleyan",
  entrydisp2: "WPI",
  entrydisp3: "Colby",
  entrydisp4: "Hamilton",
  entrydisp5: "",
  entrydisp6: "",
  results_code_display:
    "   Entry                  Time    from Win from Prev\r   -------------------- --------- -------- ---------\r1  Wesleyan             5:54.6                      \r2  WPI                  6:01.21       6.61      6.61\r3  Hamilton             6:07.29      12.69      6.08\r4  Colby                6:09.5        14.9      2.21\r\r",
  racedateUnix: "2024-04-06",
  entryseed6: "",
  order0: "",
  order1: 1,
  order2: 2,
  order3: 4,
  order4: 3,
  order5: "",
  order6: "",
  splitprev0: "",
  splitprev1: "",
  splitprev2: 6.61,
  splitprev3: 2.21,
  splitprev4: 6.08,
  splitprev5: "",
  splitprev6: "",
  splitwin0: "",
  splitwin1: "",
  splitwin2: 6.61,
  splitwin3: 14.9,
  splitwin4: 12.69,
  splitwin5: "",
  splitwin6: "",
  time0: "",
  time1: "5:54.6",
  time2: "6:01.21",
  time3: "6:09.5",
  time4: "6:07.29",
  time5: "",
  time6: "",
  SummaryHTML:
    "<tr><td>1</td><td>Wesleyan</td><td>5:54.6</td><td align='right'></td><td align='right'></td></tr><tr><td>2</td><td>WPI</td><td>6:01.21</td><td align='right'>6.61</td><td align='right'>6.61</td></tr><tr><td>3</td><td>Hamilton</td><td>6:07.29</td><td align='right'>12.69</td><td align='right'>6.08</td></tr><tr><td>4</td><td>Colby</td><td>6:09.5</td><td align='right'>14.9</td><td align='right'>2.21</td></tr>",
  competitorList:
    "WPI, Colby, Hamilton, Wesleyan, 1st H1, 2nd H1, 3rd H1, 4th H1, 5th H1, 6th H1, 1st H2, 2nd H2, 3rd H2, 4th H2, 5th H2, 6th H2",
};

export const WPI_MV8_NO_ENTRIES: LakeScheduleLanesEntry = {
  id: 31951,
  lk_schd_id: 2389,
  racetime: "09:40:00",
  event: "MV8",
  host: "WPI",
  entry0: "",
  entry1: "",
  entry2: "",
  entry3: "",
  entry4: "",
  entry5: "",
  entry6: "",
  racedate: "04/06/2024",
  racedatetime: "04/06/2024 09:40:00",
  clbType: "Col",
  entryseed0: "",
  entryseed1: "",
  entryseed2: "",
  entryseed3: "",
  entryseed4: "",
  entryseed5: "",
  gcal_error: "",
  gcal_eTag: "",
  gcal_status: "",
  entrydisp0: "",
  entrydisp1: "",
  entrydisp2: "",
  entrydisp3: "",
  entrydisp4: "",
  entrydisp5: "",
  entrydisp6: "",
  results_code_display: "",
  racedateUnix: "",
  entryseed6: "",
  order0: "",
  order1: "",
  order2: "",
  order3: "",
  order4: "",
  order5: "",
  order6: "",
  splitprev0: "",
  splitprev1: "",
  splitprev2: "",
  splitprev3: "",
  splitprev4: "",
  splitprev5: "",
  splitprev6: "",
  splitwin0: "",
  splitwin1: "",
  splitwin2: "",
  splitwin3: "",
  splitwin4: "",
  splitwin5: "",
  splitwin6: "",
  time0: "",
  time1: "",
  time2: "",
  time3: "",
  time4: "",
  time5: "",
  time6: "",
  SummaryHTML: "",
  competitorList: "",
};

export const EMPTY_ENTRY: LakeScheduleLanesEntry = {
  id: 31951,
  lk_schd_id: 2389,
  racetime: "09:40:00",
  event: "",
  host: "",
  entry0: "",
  entry1: "",
  entry2: "",
  entry3: "",
  entry4: "",
  entry5: "",
  entry6: "",
  racedate: "",
  racedatetime: "",
  clbType: "Col",
  entryseed0: "",
  entryseed1: "",
  entryseed2: "",
  entryseed3: "",
  entryseed4: "",
  entryseed5: "",
  gcal_error: "",
  gcal_eTag: "",
  gcal_status: "",
  entrydisp0: "",
  entrydisp1: "",
  entrydisp2: "",
  entrydisp3: "",
  entrydisp4: "",
  entrydisp5: "",
  entrydisp6: "",
  results_code_display: "",
  racedateUnix: "",
  entryseed6: "",
  order0: "",
  order1: "",
  order2: "",
  order3: "",
  order4: "",
  order5: "",
  order6: "",
  splitprev0: "",
  splitprev1: "",
  splitprev2: "",
  splitprev3: "",
  splitprev4: "",
  splitprev5: "",
  splitprev6: "",
  splitwin0: "",
  splitwin1: "",
  splitwin2: "",
  splitwin3: "",
  splitwin4: "",
  splitwin5: "",
  splitwin6: "",
  time0: "",
  time1: "",
  time2: "",
  time3: "",
  time4: "",
  time5: "",
  time6: "",
  SummaryHTML: "",
  competitorList: "",
};

export const ASSUMPTION_W3V8_DNF: LakeScheduleLanesEntry = {
  id: 31676,
  lk_schd_id: 2362,
  racetime: "08:30:00",
  event: "W3V8",
  host: "Assumption",
  entry0: "",
  entry1: "",
  entry2: "",
  entry3: "Mt. Holyoke College",
  entry4: "Coast Guard",
  entry5: "Assumption",
  entry6: "",
  racedate: "04/22/2023",
  racedatetime: "04/22/2023 08:30:00",
  clbType: "Col",
  entryseed0: "",
  entryseed1: "",
  entryseed2: "",
  entryseed3: "",
  entryseed4: "",
  entryseed5: "",
  gcal_error: "",
  gcal_eTag: "",
  gcal_status: "",
  entrydisp0: "",
  entrydisp1: "",
  entrydisp2: "",
  entrydisp3: "Mt. Holyoke College",
  entrydisp4: "Coast Guard",
  entrydisp5: "Assumption",
  entrydisp6: "",
  results_code_display:
    "   Entry                  Time    from Win from Prev\r   -------------------- --------- -------- ---------\r1  Mt. Holyoke College  8:24.55                     \r2  Assumption           8:28.15        3.6       3.6\r\r",
  racedateUnix: "2023-04-22",
  entryseed6: "",
  order0: "",
  order1: "",
  order2: "",
  order3: 1,
  order4: "",
  order5: 2,
  order6: "",
  splitprev0: "",
  splitprev1: "",
  splitprev2: "",
  splitprev3: "",
  splitprev4: "",
  splitprev5: 3.6,
  splitprev6: "",
  splitwin0: "",
  splitwin1: "",
  splitwin2: "",
  splitwin3: "",
  splitwin4: "",
  splitwin5: 3.6,
  splitwin6: "",
  time0: "",
  time1: "",
  time2: "",
  time3: "8:24.55",
  time4: "DNF",
  time5: "8:28.15",
  time6: "",
  SummaryHTML:
    "<tr><td>1</td><td>Mt. Holyoke College</td><td>8:24.55</td><td align='right'></td><td align='right'></td></tr><tr><td>2</td><td>Assumption</td><td>8:28.15</td><td align='right'>3.6</td><td align='right'>3.6</td></tr>",
  competitorList:
    "Assumption, Mt. Holyoke College, Coast Guard, 1st H1, 2nd H1, 3rd H1, 4th H1, 5th H1, 6th H1, 1st H2, 2nd H2, 3rd H2, 4th H2, 5th H2, 6th H2",
};

export const WPI_W2V8_SCR: LakeScheduleLanesEntry = {
  id: 29582,
  lk_schd_id: 1955,
  racetime: "08:50:00",
  event: "W2V8",
  host: "WPI",
  entry0: "",
  entry1: "Tufts",
  entry2: "WPI",
  entry3: "William Smith",
  entry4: "Clark",
  entry5: "Skidmore",
  entry6: "",
  racedate: "04/22/2018",
  racedatetime: "04/22/2018 08:50:00",
  clbType: "Col",
  entryseed0: "",
  entryseed1: "",
  entryseed2: "",
  entryseed3: "",
  entryseed4: "",
  entryseed5: "",
  gcal_error: "",
  gcal_eTag: "",
  gcal_status: "",
  entrydisp0: "",
  entrydisp1: "Tufts",
  entrydisp2: "WPI",
  entrydisp3: "William Smith",
  entrydisp4: "Clark",
  entrydisp5: "Skidmore",
  entrydisp6: "",
  results_code_display:
    "   Entry                  Time    from Win from Prev\r   -------------------- --------- -------- ---------\r1  WPI                  7:04.1                      \r2  Tufts                7:04.24        .14       .14\r3  William Smith        7:18.39      14.29     14.15\r4  Clark                8:07.76      63.66     49.37\r\r",
  racedateUnix: "2018-04-22",
  entryseed6: "",
  order0: "",
  order1: 2,
  order2: 1,
  order3: 3,
  order4: 4,
  order5: "",
  order6: "",
  splitprev0: "",
  splitprev1: 0.14,
  splitprev2: "",
  splitprev3: 14.15,
  splitprev4: 49.37,
  splitprev5: "",
  splitprev6: "",
  splitwin0: "",
  splitwin1: 0.14,
  splitwin2: "",
  splitwin3: 14.29,
  splitwin4: 63.66,
  splitwin5: "",
  splitwin6: "",
  time0: "",
  time1: "7:04.24",
  time2: "7:04.1",
  time3: "7:18.39",
  time4: "8:07.76",
  time5: "SCR",
  time6: "",
  SummaryHTML:
    "<tr><td>1</td><td>WPI</td><td>7:04.1</td><td align='right'></td><td align='right'></td></tr><tr><td>2</td><td>Tufts</td><td>7:04.24</td><td align='right'>.14</td><td align='right'></td></tr><tr><td>3</td><td>William Smith</td><td>7:18.39</td><td align='right'>14.29</td><td align='right'>14.15</td></tr><tr><td>4</td><td>Clark</td><td>8:07.76</td><td align='right'>63.66</td><td align='right'>49.37</td></tr>",
  competitorList:
    "WPI, Clark, Skidmore, Tufts, William Smith, WPI, 1st H1, 2nd H1, 3rd H1, 4th H1, 5th H1, 6th H1, 1st H2, 2nd H2, 3rd H2, 4th H2, 5th H2, 6th H2",
};

export const WPI_MV4_SEED: LakeScheduleLanesEntry = {
  id: 30008,
  lk_schd_id: 2004,
  racetime: "10:00:00",
  event: "MV4+",
  host: "WPI",
  entry0: "",
  entry1: "WPI",
  entry2: "Hamilton",
  entry3: "WPI",
  entry4: "Conn College",
  entry5: "",
  entry6: "",
  racedate: "04/07/2019",
  racedatetime: "04/07/2019 10:00:00",
  clbType: "Col",
  entryseed0: "",
  entryseed1: "A",
  entryseed2: "",
  entryseed3: "B",
  entryseed4: "",
  entryseed5: "",
  gcal_error: "",
  gcal_eTag: "",
  gcal_status: "",
  entrydisp0: "",
  entrydisp1: "WPI A",
  entrydisp2: "Hamilton",
  entrydisp3: "WPI B",
  entrydisp4: "Conn College",
  entrydisp5: "",
  entrydisp6: "",
  results_code_display:
    "   Entry                  Time    from Win from Prev\r   -------------------- --------- -------- ---------\r1  WPI A                7:45.40                     \r2  WPI B                7:55.5        10.1      10.1\r3  Hamilton             8:01.53      16.13      6.03\r4  Conn College         9:15.7        90.3     74.17\r\r",
  racedateUnix: "2019-04-07",
  entryseed6: "",
  order0: "",
  order1: 1,
  order2: 3,
  order3: 2,
  order4: 4,
  order5: "",
  order6: "",
  splitprev0: "",
  splitprev1: "",
  splitprev2: 6.03,
  splitprev3: 10.1,
  splitprev4: 74.17,
  splitprev5: "",
  splitprev6: "",
  splitwin0: "",
  splitwin1: "",
  splitwin2: 16.13,
  splitwin3: 10.1,
  splitwin4: 90.3,
  splitwin5: "",
  splitwin6: "",
  time0: "",
  time1: "7:45.40",
  time2: "8:01.53",
  time3: "7:55.5",
  time4: "9:15.7",
  time5: "",
  time6: "",
  SummaryHTML:
    "<tr><td>1</td><td>WPI A</td><td>7:45.40</td><td align='right'></td><td align='right'></td></tr><tr><td>2</td><td>WPI B</td><td>7:55.5</td><td align='right'>10.1</td><td align='right'>10.1</td></tr><tr><td>3</td><td>Hamilton</td><td>8:01.53</td><td align='right'>16.13</td><td align='right'>6.03</td></tr><tr><td>4</td><td>Conn College</td><td>9:15.7</td><td align='right'>90.3</td><td align='right'>74.17</td></tr>",
  competitorList:
    "WPI, Assumption, Clark, JWU, Hamilton, MHC, Simmons, Wash College, 1st H1, 2nd H1, 3rd H1, 4th H1, 5th H1, 6th H1, 1st H2, 2nd H2, 3rd H2, 4th H2, 5th H2, 6th H2",
};

export const WPI_W4V8_SEED: LakeScheduleLanesEntry = {
  id: 31164,
  lk_schd_id: 2293,
  racetime: "10:00:00",
  event: "W4V8",
  host: "WPI",
  entry0: "",
  entry1: "WPI",
  entry2: "Bates",
  entry3: "Bates",
  entry4: "",
  entry5: "",
  entry6: "",
  racedate: "04/10/2022",
  racedatetime: "04/10/2022 10:00:00",
  clbType: "Col",
  entryseed0: "",
  entryseed1: "",
  entryseed2: "",
  entryseed3: "B",
  entryseed4: "",
  entryseed5: "",
  gcal_error: "",
  gcal_eTag: "",
  gcal_status: "",
  entrydisp0: "",
  entrydisp1: "WPI",
  entrydisp2: "Bates",
  entrydisp3: "Bates B",
  entrydisp4: "",
  entrydisp5: "",
  entrydisp6: "",
  results_code_display:
    "   Entry                  Time    from Win from Prev\r   -------------------- --------- -------- ---------\r1  Bates                7:23.88                     \r2  Bates B              7:58.09      34.21     34.21\r3  WPI                  8:20.03      56.15     21.94\r\r",
  racedateUnix: "2022-04-10",
  entryseed6: "",
  order0: "",
  order1: 3,
  order2: 1,
  order3: 2,
  order4: "",
  order5: "",
  order6: "",
  splitprev0: "",
  splitprev1: 21.94,
  splitprev2: "",
  splitprev3: 34.21,
  splitprev4: "",
  splitprev5: "",
  splitprev6: "",
  splitwin0: "",
  splitwin1: 56.15,
  splitwin2: "",
  splitwin3: 34.21,
  splitwin4: "",
  splitwin5: "",
  splitwin6: "",
  time0: "",
  time1: "8:20.03",
  time2: "7:23.88",
  time3: "7:58.09",
  time4: "",
  time5: "",
  time6: "",
  SummaryHTML:
    "<tr><td>1</td><td>Bates</td><td>7:23.88</td><td align='right'></td><td align='right'></td></tr><tr><td>2</td><td>Bates B</td><td>7:58.09</td><td align='right'>34.21</td><td align='right'>34.21</td></tr><tr><td>3</td><td>WPI</td><td>8:20.03</td><td align='right'>56.15</td><td align='right'>21.94</td></tr>",
  competitorList:
    "WPI, Bates, Hamilton, RIT, Washington College, 1st H1, 2nd H1, 3rd H1, 4th H1, 5th H1, 6th H1, 1st H2, 2nd H2, 3rd H2, 4th H2, 5th H2, 6th H2",
};

export const HCR_WV4_SEED_NO_A_BLANK_TIME: LakeScheduleLanesEntry = {
  id: 29430,
  lk_schd_id: 1969,
  racetime: "09:30:00",
  event: "WV4+",
  host: "Holy Cross",
  entry0: "",
  entry1: "University of Connecticut B",
  entry2: "Boston College",
  entry3: "         ",
  entry4: "",
  entry5: "",
  entry6: "",
  racedate: "04/08/2018",
  racedatetime: "04/08/2018 09:30:00",
  clbType: "Col",
  entryseed0: "",
  entryseed1: "",
  entryseed2: "",
  entryseed3: "",
  entryseed4: "",
  entryseed5: "",
  gcal_error: "",
  gcal_eTag: "",
  gcal_status: "",
  entrydisp0: "",
  entrydisp1: "University of Connecticut B",
  entrydisp2: "Boston College",
  entrydisp3: "         ",
  entrydisp4: "",
  entrydisp5: "",
  entrydisp6: "",
  results_code_display:
    "   Entry                  Time    from Win from Prev\r   -------------------- --------- -------- ---------\r1  Boston College       7:33.9                      \r2  University of Connec 7:54.5        20.6      20.6\r3                       8:17.64      43.74     23.14\r\r",
  racedateUnix: "2018-04-08",
  entryseed6: "",
  order0: "",
  order1: 2,
  order2: 1,
  order3: 3,
  order4: "",
  order5: "",
  order6: "",
  splitprev0: "",
  splitprev1: 20.6,
  splitprev2: "",
  splitprev3: 23.14,
  splitprev4: "",
  splitprev5: "",
  splitprev6: "",
  splitwin0: "",
  splitwin1: 20.6,
  splitwin2: "",
  splitwin3: 43.74,
  splitwin4: "",
  splitwin5: "",
  splitwin6: "",
  time0: "",
  time1: "7:54.5",
  time2: "7:33.9",
  time3: "8:17.64",
  time4: "",
  time5: "",
  time6: "",
  SummaryHTML:
    "<tr><td>1</td><td>Boston College</td><td>7:33.9</td><td align='right'></td><td align='right'></td></tr><tr><td>2</td><td>University of Connecticut B</td><td>7:54.5</td><td align='right'>20.6</td><td align='right'></td></tr><tr><td>3</td><td>         </td><td>8:17.64</td><td align='right'>43.74</td><td align='right'>23.14</td></tr>",
  competitorList: "",
};

export const WPI_WV8_BLANK_ENTRY: LakeScheduleLanesEntry = {
  id: 29442,
  lk_schd_id: 1951,
  racetime: "08:50:00",
  event: "WV8",
  host: "WPI HEAT",
  entry0: "         ",
  entry1: "Bates",
  entry2: "Hamilton",
  entry3: "MHC",
  entry4: "",
  entry5: "",
  entry6: "",
  racedate: "04/08/2018",
  racedatetime: "04/08/2018 08:50:00",
  clbType: "Col",
  entryseed0: "",
  entryseed1: "",
  entryseed2: "",
  entryseed3: "",
  entryseed4: "",
  entryseed5: "",
  gcal_error: "",
  gcal_eTag: "",
  gcal_status: "",
  entrydisp0: "         ",
  entrydisp1: "Bates",
  entrydisp2: "Hamilton",
  entrydisp3: "MHC",
  entrydisp4: "",
  entrydisp5: "",
  entrydisp6: "",
  results_code_display:
    "   Entry                  Time    from Win from Prev\r   -------------------- --------- -------- ---------\r1  Bates                6:47.97                     \r2  Hamilton             6:51.39       3.42      3.42\r3  MHC                  7:41.87       53.9     50.48\r\r",
  racedateUnix: "2018-04-08",
  entryseed6: "",
  order0: "",
  order1: 1,
  order2: 2,
  order3: 3,
  order4: "",
  order5: "",
  order6: "",
  splitprev0: "",
  splitprev1: "",
  splitprev2: 3.42,
  splitprev3: 50.48,
  splitprev4: "",
  splitprev5: "",
  splitprev6: "",
  splitwin0: "",
  splitwin1: "",
  splitwin2: 3.42,
  splitwin3: 53.9,
  splitwin4: "",
  splitwin5: "",
  splitwin6: "",
  time0: "",
  time1: "6:47.97",
  time2: "6:51.39",
  time3: "7:41.87",
  time4: "",
  time5: "",
  time6: "",
  SummaryHTML:
    "<tr><td>1</td><td>Bates</td><td>6:47.97</td><td align='right'></td><td align='right'></td></tr><tr><td>2</td><td>Hamilton</td><td>6:51.39</td><td align='right'>3.42</td><td align='right'>3.42</td></tr><tr><td>3</td><td>MHC</td><td>7:41.87</td><td align='right'>53.9</td><td align='right'>50.48</td></tr>",
  competitorList: "",
};
