import { LakeScheduleLanesEntry } from "../../../../src/file-maker/types/duel-types.ts";

export const BREAK_HOST: LakeScheduleLanesEntry = {
  id: 31959,
  lk_schd_id: "",
  racetime: "11:00:00",
  event: "",
  host: "Break",
  entry0: "",
  entry1: "",
  entry2: "",
  entry3: "",
  entry4: "",
  entry5: "",
  entry6: "",
  racedate: "04/06/2024",
  racedatetime: "04/06/2024 11:00:00",
  clbType: "Col",
  entryseed0: "",
  entryseed1: "",
  entryseed2: "",
  entryseed3: "",
  entryseed4: "",
  entryseed5: "",
  gcal_error: "",
  gcal_eTag: "",
  gcal_status: "",
  entrydisp0: "",
  entrydisp1: "",
  entrydisp2: "",
  entrydisp3: "",
  entrydisp4: "",
  entrydisp5: "",
  entrydisp6: "",
  results_code_display: "Ln  Entry               \r-- --------------------\r",
  racedateUnix: "2024-04-06",
  entryseed6: "",
  order0: "",
  order1: "",
  order2: "",
  order3: "",
  order4: "",
  order5: "",
  order6: "",
  splitprev0: "",
  splitprev1: "",
  splitprev2: "",
  splitprev3: "",
  splitprev4: "",
  splitprev5: "",
  splitprev6: "",
  splitwin0: "",
  splitwin1: "",
  splitwin2: "",
  splitwin3: "",
  splitwin4: "",
  splitwin5: "",
  splitwin6: "",
  time0: "",
  time1: "",
  time2: "",
  time3: "",
  time4: "",
  time5: "",
  time6: "",
  SummaryHTML: "",
  competitorList: "",
};

export const WESLEYEAN_BREAK: LakeScheduleLanesEntry = {
  id: 152395,
  lk_schd_id: 160,
  racetime: "08:30:00",
  event: "Break",
  host: "Wesleyan",
  entry0: "",
  entry1: "",
  entry2: "",
  entry3: "",
  entry4: "",
  entry5: "",
  entry6: "",
  racedate: "04/29/2006",
  racedatetime: "04/29/2006 08:30:00",
  clbType: "",
  entryseed0: "",
  entryseed1: "",
  entryseed2: "",
  entryseed3: "",
  entryseed4: "",
  entryseed5: "",
  gcal_error: "",
  gcal_eTag: "",
  gcal_status: "",
  entrydisp0: "",
  entrydisp1: "",
  entrydisp2: "",
  entrydisp3: "",
  entrydisp4: "",
  entrydisp5: "",
  entrydisp6: "",
  results_code_display: "Ln  Entry               \r-- --------------------\r",
  racedateUnix: "2006-04-29",
  entryseed6: "",
  order0: "",
  order1: "",
  order2: "",
  order3: "",
  order4: "",
  order5: "",
  order6: "",
  splitprev0: "",
  splitprev1: "",
  splitprev2: "",
  splitprev3: "",
  splitprev4: "",
  splitprev5: "",
  splitprev6: "",
  splitwin0: "",
  splitwin1: "",
  splitwin2: "",
  splitwin3: "",
  splitwin4: "",
  splitwin5: "",
  splitwin6: "",
  time0: "",
  time1: "",
  time2: "",
  time3: "",
  time4: "",
  time5: "",
  time6: "",
  SummaryHTML: "",
  competitorList:
    "Wesleyan, Trinity, Conn College, Clark, , 1st H1, 2nd H1, 3rd H1, 4th H1, 5th H1, 6th H1, 1st H2, 2nd H2, 3rd H2, 4th H2, 5th H2, 6th H2",
};

export const WPI_BREAK: LakeScheduleLanesEntry = {
  id: 152242,
  lk_schd_id: 19,
  racetime: "09:00:00",
  event: "Break",
  host: "WPI",
  entry0: "",
  entry1: "",
  entry2: "",
  entry3: "",
  entry4: "",
  entry5: "",
  entry6: "",
  racedate: "04/15/2006",
  racedatetime: "04/15/2006 09:00:00",
  clbType: "",
  entryseed0: "",
  entryseed1: "",
  entryseed2: "",
  entryseed3: "",
  entryseed4: "",
  entryseed5: "",
  gcal_error: "",
  gcal_eTag: "",
  gcal_status: "",
  entrydisp0: "",
  entrydisp1: "",
  entrydisp2: "",
  entrydisp3: "",
  entrydisp4: "",
  entrydisp5: "",
  entrydisp6: "",
  results_code_display: "Ln  Entry               \r-- --------------------\r",
  racedateUnix: "2006-04-15",
  entryseed6: "",
  order0: "",
  order1: "",
  order2: "",
  order3: "",
  order4: "",
  order5: "",
  order6: "",
  splitprev0: "",
  splitprev1: "",
  splitprev2: "",
  splitprev3: "",
  splitprev4: "",
  splitprev5: "",
  splitprev6: "",
  splitwin0: "",
  splitwin1: "",
  splitwin2: "",
  splitwin3: "",
  splitwin4: "",
  splitwin5: "",
  splitwin6: "",
  time0: "",
  time1: "",
  time2: "",
  time3: "",
  time4: "",
  time5: "",
  time6: "",
  SummaryHTML: "",
  competitorList:
    "WPI, Williams, Conn College, 1st H1, 2nd H1, 3rd H1, 4th H1, 5th H1, 6th H1, 1st H2, 2nd H2, 3rd H2, 4th H2, 5th H2, 6th H2",
};
