import { LakeScheduleLanesEntry } from "../../../../src/file-maker/types/duel-types.ts";

export const CLARK_WV8_GF: LakeScheduleLanesEntry = {
  id: 31982,
  lk_schd_id: 2384,
  racetime: "09:50:00",
  host: "Clark",
  event: "WV8 GF",
  entry0: "",
  entry1: "1st H1",
  entry2: "1st H2",
  entry3: "2nd H1",
  entry4: "2nd H2",
  entry5: "5th Fastest",
  entry6: "6th Fastest",
  racedate: "04/13/2024",
  racedatetime: "04/13/2024 09:50:00",
  clbType: "Col",
  entryseed0: "",
  entryseed1: "",
  entryseed2: "",
  entryseed3: "",
  entryseed4: "",
  entryseed5: "",
  gcal_error: "",
  gcal_eTag: "",
  gcal_status: "",
  entrydisp0: "",
  entrydisp1: "1st H1",
  entrydisp2: "1st H2",
  entrydisp3: "2nd H1",
  entrydisp4: "2nd H2",
  entrydisp5: "5th Fastest",
  entrydisp6: "6th Fastest",
  results_code_display:
    "Ln  Entry               \r-- --------------------\r1  1st H1\r2  1st H2\r3  2nd H1\r4  2nd H2\r5  5th Fastest\r6  6th Fastest\r",
  racedateUnix: "2024-04-13",
  entryseed6: "",
  order0: "",
  order1: "",
  order2: "",
  order3: "",
  order4: "",
  order5: "",
  order6: "",
  splitprev0: "",
  splitprev1: "",
  splitprev2: "",
  splitprev3: "",
  splitprev4: "",
  splitprev5: "",
  splitprev6: "",
  splitwin0: "",
  splitwin1: "",
  splitwin2: "",
  splitwin3: "",
  splitwin4: "",
  splitwin5: "",
  splitwin6: "",
  time0: "",
  time1: "",
  time2: "",
  time3: "",
  time4: "",
  time5: "",
  time6: "",
  SummaryHTML:
    "<tr><td>1</td><td>1st H1</td><td>&nbsp;</td><td align='right'>&nbsp;</td><td align='right'>&nbsp;</td></tr><tr><td>2</td><td>1st H2</td><td>&nbsp;</td><td align='right'>&nbsp;</td><td align='right'>&nbsp;</td></tr><tr><td>3</td><td>2nd H1</td><td>&nbsp;</td><td align='right'>&nbsp;</td><td align='right'>&nbsp;</td></tr><tr><td>4</td><td>2nd H2</td><td>&nbsp;</td><td align='right'>&nbsp;</td><td align='right'>&nbsp;</td></tr><tr><td>5</td><td>5th Fastest</td><td>&nbsp;</td><td align='right'>&nbsp;</td><td align='right'>&nbsp;</td></tr><tr><td>6</td><td>6th Fastest</td><td>&nbsp;</td><td align='right'>&nbsp;</td><td align='right'>&nbsp;</td></tr>",
  competitorList:
    "Clark, MT Holyoke, 1st H1, 2nd H1, 3rd H1, 4th H1, 5th H1, 6th H1, 1st H2, 2nd H2, 3rd H2, 4th H2, 5th H2, 6th H2",
};

export const HCR_WV8: LakeScheduleLanesEntry = {
  id: 31984,
  lk_schd_id: 2416,
  racetime: "10:10:00",
  event: "WV8",
  host: "Holy Cross",
  entry0: "",
  entry1: "Holy Cross",
  entry2: "Smith",
  entry3: "Colgate",
  entry4: "",
  entry5: "",
  entry6: "",
  racedate: "04/13/2024",
  racedatetime: "04/13/2024 10:10:00",
  clbType: "Col",
  entryseed0: "",
  entryseed1: "",
  entryseed2: "",
  entryseed3: "",
  entryseed4: "",
  entryseed5: "",
  gcal_error: "",
  gcal_eTag: "",
  gcal_status: "",
  entrydisp0: "",
  entrydisp1: "Holy Cross",
  entrydisp2: "Smith",
  entrydisp3: "Colgate",
  entrydisp4: "",
  entrydisp5: "",
  entrydisp6: "",
  results_code_display:
    "Ln  Entry               \r-- --------------------\r1  Holy Cross\r2  Smith\r3  Colgate\r",
  racedateUnix: "2024-04-13",
  entryseed6: "",
  order0: "",
  order1: "",
  order2: "",
  order3: "",
  order4: "",
  order5: "",
  order6: "",
  splitprev0: "",
  splitprev1: "",
  splitprev2: "",
  splitprev3: "",
  splitprev4: "",
  splitprev5: "",
  splitprev6: "",
  splitwin0: "",
  splitwin1: "",
  splitwin2: "",
  splitwin3: "",
  splitwin4: "",
  splitwin5: "",
  splitwin6: "",
  time0: "",
  time1: "",
  time2: "",
  time3: "",
  time4: "",
  time5: "",
  time6: "",
  SummaryHTML:
    "<tr><td>1</td><td>Holy Cross</td><td>&nbsp;</td><td align='right'>&nbsp;</td><td align='right'>&nbsp;</td></tr><tr><td>2</td><td>Smith</td><td>&nbsp;</td><td align='right'>&nbsp;</td><td align='right'>&nbsp;</td></tr><tr><td>3</td><td>Colgate</td><td>&nbsp;</td><td align='right'>&nbsp;</td><td align='right'>&nbsp;</td></tr>",
  competitorList:
    "Holy Cross, Holy Cross, Colgate, Smith, 1st fastest, 2nd fastest, 3rd fastest, 1st H1, 2nd H1, 3rd H1, 4th H1, 5th H1, 6th H1, 1st H2, 2nd H2, 3rd H2, 4th H2, 5th H2, 6th H2",
};

export const WPI_MV8_RESULTS: LakeScheduleLanesEntry = {
  id: 31951,
  lk_schd_id: 2389,
  racetime: "09:40:00",
  event: "MV8",
  host: "WPI",
  entry0: "",
  entry1: "Wesleyan",
  entry2: "WPI",
  entry3: "Colby",
  entry4: "Hamilton",
  entry5: "",
  entry6: "",
  racedate: "04/06/2024",
  racedatetime: "04/06/2024 09:40:00",
  clbType: "Col",
  entryseed0: "",
  entryseed1: "",
  entryseed2: "",
  entryseed3: "",
  entryseed4: "",
  entryseed5: "",
  gcal_error: "",
  gcal_eTag: "",
  gcal_status: "",
  entrydisp0: "",
  entrydisp1: "Wesleyan",
  entrydisp2: "WPI",
  entrydisp3: "Colby",
  entrydisp4: "Hamilton",
  entrydisp5: "",
  entrydisp6: "",
  results_code_display:
    "   Entry                  Time    from Win from Prev\r   -------------------- --------- -------- ---------\r1  Wesleyan             5:54.6                      \r2  WPI                  6:01.21       6.61      6.61\r3  Hamilton             6:07.29      12.69      6.08\r4  Colby                6:09.5        14.9      2.21\r\r",
  racedateUnix: "2024-04-06",
  entryseed6: "",
  order0: "",
  order1: 1,
  order2: 2,
  order3: 4,
  order4: 3,
  order5: "",
  order6: "",
  splitprev0: "",
  splitprev1: "",
  splitprev2: 6.61,
  splitprev3: 2.21,
  splitprev4: 6.08,
  splitprev5: "",
  splitprev6: "",
  splitwin0: "",
  splitwin1: "",
  splitwin2: 6.61,
  splitwin3: 14.9,
  splitwin4: 12.69,
  splitwin5: "",
  splitwin6: "",
  time0: "",
  time1: "5:54.6",
  time2: "6:01.21",
  time3: "6:09.5",
  time4: "6:07.29",
  time5: "",
  time6: "",
  SummaryHTML:
    "<tr><td>1</td><td>Wesleyan</td><td>5:54.6</td><td align='right'></td><td align='right'></td></tr><tr><td>2</td><td>WPI</td><td>6:01.21</td><td align='right'>6.61</td><td align='right'>6.61</td></tr><tr><td>3</td><td>Hamilton</td><td>6:07.29</td><td align='right'>12.69</td><td align='right'>6.08</td></tr><tr><td>4</td><td>Colby</td><td>6:09.5</td><td align='right'>14.9</td><td align='right'>2.21</td></tr>",
  competitorList:
    "WPI, Colby, Hamilton, Wesleyan, 1st H1, 2nd H1, 3rd H1, 4th H1, 5th H1, 6th H1, 1st H2, 2nd H2, 3rd H2, 4th H2, 5th H2, 6th H2",
};

export const WPI_MV8_NO_ENTRIES: LakeScheduleLanesEntry = {
  id: 31951,
  lk_schd_id: 2389,
  racetime: "09:40:00",
  event: "MV8",
  host: "WPI",
  entry0: "",
  entry1: "",
  entry2: "",
  entry3: "",
  entry4: "",
  entry5: "",
  entry6: "",
  racedate: "04/06/2024",
  racedatetime: "04/06/2024 09:40:00",
  clbType: "Col",
  entryseed0: "",
  entryseed1: "",
  entryseed2: "",
  entryseed3: "",
  entryseed4: "",
  entryseed5: "",
  gcal_error: "",
  gcal_eTag: "",
  gcal_status: "",
  entrydisp0: "",
  entrydisp1: "",
  entrydisp2: "",
  entrydisp3: "",
  entrydisp4: "",
  entrydisp5: "",
  entrydisp6: "",
  results_code_display: "",
  racedateUnix: "",
  entryseed6: "",
  order0: "",
  order1: "",
  order2: "",
  order3: "",
  order4: "",
  order5: "",
  order6: "",
  splitprev0: "",
  splitprev1: "",
  splitprev2: "",
  splitprev3: "",
  splitprev4: "",
  splitprev5: "",
  splitprev6: "",
  splitwin0: "",
  splitwin1: "",
  splitwin2: "",
  splitwin3: "",
  splitwin4: "",
  splitwin5: "",
  splitwin6: "",
  time0: "",
  time1: "",
  time2: "",
  time3: "",
  time4: "",
  time5: "",
  time6: "",
  SummaryHTML: "",
  competitorList: "",
};

export const EMPTY_ENTRY: LakeScheduleLanesEntry = {
  id: 31951,
  lk_schd_id: 2389,
  racetime: "09:40:00",
  event: "",
  host: "",
  entry0: "",
  entry1: "",
  entry2: "",
  entry3: "",
  entry4: "",
  entry5: "",
  entry6: "",
  racedate: "",
  racedatetime: "",
  clbType: "Col",
  entryseed0: "",
  entryseed1: "",
  entryseed2: "",
  entryseed3: "",
  entryseed4: "",
  entryseed5: "",
  gcal_error: "",
  gcal_eTag: "",
  gcal_status: "",
  entrydisp0: "",
  entrydisp1: "",
  entrydisp2: "",
  entrydisp3: "",
  entrydisp4: "",
  entrydisp5: "",
  entrydisp6: "",
  results_code_display: "",
  racedateUnix: "",
  entryseed6: "",
  order0: "",
  order1: "",
  order2: "",
  order3: "",
  order4: "",
  order5: "",
  order6: "",
  splitprev0: "",
  splitprev1: "",
  splitprev2: "",
  splitprev3: "",
  splitprev4: "",
  splitprev5: "",
  splitprev6: "",
  splitwin0: "",
  splitwin1: "",
  splitwin2: "",
  splitwin3: "",
  splitwin4: "",
  splitwin5: "",
  splitwin6: "",
  time0: "",
  time1: "",
  time2: "",
  time3: "",
  time4: "",
  time5: "",
  time6: "",
  SummaryHTML: "",
  competitorList: "",
};
