name: Deploy
on:
  push:
    branches: main

# Concurrency group name ensures concurrent workflow runs wait for any in-progress job to finish
concurrency:
  group: merge-${{ github.ref }}

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  lint:
    name: "Lint App"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: "./github/workflows/lint.yaml"
  codeql:
    name: "CodeQL"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: "./github/workflows/codeql.yaml"
  deploy:
    needs: [lint, codeql]
    name: "Deploy App"
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: https://d3qny3i081io7i.cloudfront.net/
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: "./.github/setup"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{secrets.AWS_ACCOUNT_ID}}:role/${{vars.PROD_GITHUB_ROLE}}
          role-duration-seconds: 3600
          aws-region: ${{vars.PROD_AWS_REGION}}

      - name: Deploy app
        env:
          PROD_GITHUB_ORG: ${{github.repository_owner}}
          PROD_GITHUB_REPO: ${{github.event.repository.name}}
          PROD_GITHUB_ROLE: ${{vars.PROD_GITHUB_ROLE}}
        run: pnpm sst deploy --stage prod
