name: Lint
on:
  workflow_call:
  pull_request:
    branches:
      - main
      - dev

jobs:
  lint:
    name: "Lint App"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: "./.github/setup"

      - name: Run Linter
        run: pnpm turbo lint
