name: Test
on:
  workflow_call:
  pull_request:
    branches:
      - main
      - dev

permissions:
  contents: read # This is required for actions/checkout

jobs:
  lint:
    name: "Test App"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: "./.github/setup"

      - name: Cache Turbo
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/.turbo
          # Generate a new hash for every commit
          key: ${{ runner.os }}-turbo-test-${{ github.sha }}
          # But restore the cache as long as we're on the same OS
          restore-keys: |
            ${{ runner.os }}-turbo-test

      - name: Run Test
        run: pnpm turbo test --cache-dir=.turbo
